(function(){
  const $ = (id) => document.getElementById(id);
  const tabs = [...document.querySelectorAll('.nav-tab')];
  const panels = [...document.querySelectorAll('.view-panel')];

  function setView(id){
    panels.forEach(p => p.classList.toggle('active-view', p.id === id));
    tabs.forEach(t => t.classList.toggle('active', t.dataset.view === id));
  }
  tabs.forEach(tab => tab.addEventListener('click', () => setView(tab.dataset.view)));

  // Accessibility controls: actual persistent zoom levels, not a one-time toggle.
  const root = document.documentElement;
  const savedScale = Number(localStorage.getItem('civictrack:textScale') || '1');
  let textScale = Number.isFinite(savedScale) ? Math.min(1.3, Math.max(0.85, savedScale)) : 1;
  function applyTextScale(){
    root.style.setProperty('--text-scale', textScale);
    root.style.fontSize = (16 * textScale) + 'px';
    localStorage.setItem('civictrack:textScale', String(textScale));
  }
  $('textLarger').addEventListener('click', () => { textScale = Math.min(1.3, +(textScale + 0.1).toFixed(2)); applyTextScale(); });
  $('textSmaller').addEventListener('click', () => { textScale = Math.max(0.85, +(textScale - 0.1).toFixed(2)); applyTextScale(); });
  applyTextScale();

  $('highContrast').addEventListener('click', () => {
    document.body.classList.toggle('high-contrast');
    localStorage.setItem('civictrack:contrast', document.body.classList.contains('high-contrast') ? '1' : '0');
  });
  if(localStorage.getItem('civictrack:contrast') === '1') document.body.classList.add('high-contrast');

  // Translation for the visible citizen UI. No external translation service is required.
  const translations = {
    en: {},
    hi: {publicService:'सार्वजनिक सेवा रिपोर्टिंग',language:'भाषा',reportIssue:'समस्या की रिपोर्ट करें',myComplaints:'मेरी शिकायतें',citizenService:'नागरिक सेवा',reportTitle:'नागरिक समस्या की रिपोर्ट करें',reportLead:'समस्या की तस्वीर लें, स्थान जोड़ें और तीन आसान चरणों में रिपोर्ट भेजें।',lowConnectivity:'कम कनेक्टिविटी के लिए बनाया गया',snapUpload:'फोटो लें / अपलोड करें',photoLocation:'फोटो + स्थान',categorize:'श्रेणी चुनें',typeSeverityNote:'प्रकार + गंभीरता + विवरण',submit:'जमा करें',getTrackingId:'ट्रैकिंग आईडी प्राप्त करें',location:'स्थान',confirmLocation:'समस्या का स्थान पुष्टि करें',notVerified:'सत्यापित नहीं',locationHelper:'स्थान आपके प्रमाण के साथ जोड़ा जाता है ताकि संबंधित स्थानीय प्राधिकरण साइट की पहचान कर सके।',consentText:'मैं इस रिपोर्ट के साथ अपना वर्तमान स्थान जोड़ने के लिए सहमत हूँ।',verifyLocation:'मेरा स्थान सत्यापित करें',photoEvidence:'फोटो प्रमाण',showProblem:'समस्या को स्पष्ट रूप से दिखाएँ',cameraPreview:'कैमरा पूर्वावलोकन',cameraInstruction:'समस्या की तस्वीर लेने के लिए कैमरे का उपयोग करें',openCamera:'कैमरा खोलें',takePhoto:'फोटो लें',capturedPhoto:'कैप्चर की गई फोटो',reviewBeforeSaving:'सहेजने से पहले जाँचें',issueCategory:'समस्या की श्रेणी',selectCategory:'श्रेणी चुनें',severity:'गंभीरता',describeIssue:'समस्या का विवरण दें',voiceAvailable:'ब्राउज़र में उपलब्ध होने पर आवाज़ से इनपुट दिया जा सकता है।',saveContinue:'प्रमाण सहेजें और जारी रखें',reportSavedLocal:'रिपोर्ट इस डिवाइस पर सहेजी गई',trackingReference:'आपका ट्रैकिंग संदर्भ',trackingHelper:'आगे की जानकारी के लिए इस संदर्भ का उपयोग करें। आधिकारिक विभागीय स्थिति CivicTrack सेवा से कनेक्शन के बाद उपलब्ध होगी।',savedEvidence:'सहेजा गया प्रमाण',localRecords:'आपके स्थानीय रिकॉर्ड',clearRecords:'रिकॉर्ड साफ़ करें',localRecordsHelper:'ये रिकॉर्ड इस ब्राउज़र में संग्रहीत हैं। इन्हें अपने आप किसी नगरपालिका विभाग को नहीं भेजा जाता।',complaintsLead:'इस डिवाइस पर सहेजी गई रिपोर्ट देखें और उनकी स्थानीय स्थिति जाँचें।'},
    as: {publicService:'ৰাজহুৱা সেৱা প্ৰতিবেদন',language:'ভাষা',reportIssue:'নাগৰিক সমস্যাৰ প্ৰতিবেদন',myComplaints:'মোৰ অভিযোগসমূহ',citizenService:'নাগৰিক সেৱা',reportTitle:'নাগৰিক সমস্যাৰ প্ৰতিবেদন কৰক',reportLead:'সমস্যাটোৰ ছবি তোলক, স্থান যোগ কৰক আৰু তিনিটা সহজ ধাপত প্ৰতিবেদন পঠাওক।',lowConnectivity:'কম সংযোগৰ বাবে উপযোগী',snapUpload:'ছবি তোলক / আপলোড কৰক',photoLocation:'ছবি + স্থান',categorize:'শ্ৰেণী নিৰ্ধাৰণ কৰক',typeSeverityNote:'ধৰণ + গুৰুত্ব + বিৱৰণ',submit:'দাখিল কৰক',getTrackingId:'ট্ৰেকিং আইডি লাভ কৰক',location:'স্থান',confirmLocation:'সমস্যাৰ স্থান নিশ্চিত কৰক',notVerified:'যাচাই হোৱা নাই',locationHelper:'দায়িত্বশীল স্থানীয় কৰ্তৃপক্ষই ঠাইটো চিনাক্ত কৰিব পৰাকৈ স্থানটো প্ৰমাণৰ সৈতে সংলগ্ন কৰা হয়।',consentText:'এই প্ৰতিবেদনৰ সৈতে মোৰ বৰ্তমানৰ স্থান সংলগ্ন কৰিবলৈ মই সন্মত।',verifyLocation:'মোৰ স্থান যাচাই কৰক',photoEvidence:'ছবিৰ প্ৰমাণ',showProblem:'সমস্যাটো স্পষ্টকৈ দেখুৱাওক',cameraPreview:'কেমেৰা পূৰ্বদৰ্শন',cameraInstruction:'সমস্যাটোৰ ছবি তুলিবলৈ কেমেৰা ব্যৱহাৰ কৰক',openCamera:'কেমেৰা খোলক',takePhoto:'ছবি তোলক',capturedPhoto:'তোলা ছবি',reviewBeforeSaving:'সংৰক্ষণৰ আগতে পৰীক্ষা কৰক',issueCategory:'সমস্যাৰ শ্ৰেণী',selectCategory:'শ্ৰেণী বাছক',severity:'গুৰুত্ব',describeIssue:'সমস্যাটো বৰ্ণনা কৰক',voiceAvailable:'ব্ৰাউজাৰে সমৰ্থন কৰিলে কণ্ঠ ইনপুট ব্যৱহাৰ কৰিব পাৰি।',saveContinue:'প্ৰমাণ সংৰক্ষণ কৰি আগবাঢ়ক',reportSavedLocal:'প্ৰতিবেদন এই ডিভাইচত সংৰক্ষিত',trackingReference:'আপোনাৰ ট্ৰেকিং ৰেফাৰেন্স',trackingHelper:'পিছত অনুসৰণ কৰাৰ সময়ত এই ৰেফাৰেন্স ব্যৱহাৰ কৰক। CivicTrack সেৱাৰ সৈতে সংযোগ নোহোৱালৈকে চৰকাৰী বিভাগীয় অৱস্থা উপলব্ধ নহয়।',savedEvidence:'সংৰক্ষিত প্ৰমাণ',localRecords:'আপোনাৰ স্থানীয় ৰেকৰ্ড',clearRecords:'ৰেকৰ্ড পৰিষ্কাৰ কৰক',localRecordsHelper:'এই ৰেকৰ্ডসমূহ এই ব্ৰাউজাৰত সংৰক্ষিত থাকে। ইয়াক স্বয়ংক্ৰিয়ভাৱে কোনো পৌৰ বিভাগলৈ পঠোৱা নহয়।',complaintsLead:'এই ডিভাইচত সংৰক্ষিত প্ৰতিবেদনসমূহ চাওক আৰু স্থানীয় অৱস্থা পৰীক্ষা কৰক।'},
    bn: {publicService:'জনসেবা রিপোর্টিং',language:'ভাষা',reportIssue:'সমস্যা রিপোর্ট করুন',myComplaints:'আমার অভিযোগ',citizenService:'নাগরিক পরিষেবা',reportTitle:'নাগরিক সমস্যার রিপোর্ট করুন',reportLead:'সমস্যার ছবি তুলুন, অবস্থান যোগ করুন এবং তিনটি সহজ ধাপে রিপোর্ট পাঠান।',lowConnectivity:'কম সংযোগের জন্য তৈরি',snapUpload:'ছবি তুলুন / আপলোড করুন',photoLocation:'ছবি + অবস্থান',categorize:'শ্রেণিবদ্ধ করুন',typeSeverityNote:'ধরন + গুরুত্ব + বিবরণ',submit:'জমা দিন',getTrackingId:'ট্র্যাকিং আইডি পান',location:'অবস্থান',confirmLocation:'সমস্যার অবস্থান নিশ্চিত করুন',notVerified:'যাচাই হয়নি',locationHelper:'দায়িত্বপ্রাপ্ত স্থানীয় কর্তৃপক্ষ যাতে স্থানটি শনাক্ত করতে পারে, তাই অবস্থানটি প্রমাণের সঙ্গে যুক্ত করা হয়।',consentText:'এই রিপোর্টের সঙ্গে আমার বর্তমান অবস্থান যুক্ত করতে আমি সম্মত।',verifyLocation:'আমার অবস্থান যাচাই করুন',photoEvidence:'ছবির প্রমাণ',showProblem:'সমস্যাটি স্পষ্টভাবে দেখান',cameraPreview:'ক্যামেরা প্রিভিউ',cameraInstruction:'সমস্যার ছবি তুলতে ক্যামেরা ব্যবহার করুন',openCamera:'ক্যামেরা খুলুন',takePhoto:'ছবি তুলুন',capturedPhoto:'তোলা ছবি',reviewBeforeSaving:'সংরক্ষণের আগে পরীক্ষা করুন',issueCategory:'সমস্যার শ্রেণি',selectCategory:'একটি শ্রেণি বাছুন',severity:'গুরুত্ব',describeIssue:'সমস্যাটি বর্ণনা করুন',voiceAvailable:'ব্রাউজার সমর্থন করলে ভয়েস ইনপুট ব্যবহার করা যাবে।',saveContinue:'প্রমাণ সংরক্ষণ করে চালিয়ে যান',reportSavedLocal:'রিপোর্ট এই ডিভাইসে সংরক্ষিত',trackingReference:'আপনার ট্র্যাকিং রেফারেন্স',trackingHelper:'পরবর্তী অনুসরণের সময় এই রেফারেন্স ব্যবহার করুন। CivicTrack পরিষেবার সঙ্গে সংযোগ না হওয়া পর্যন্ত সরকারি বিভাগের অবস্থা পাওয়া যাবে না।',savedEvidence:'সংরক্ষিত প্রমাণ',localRecords:'আপনার স্থানীয় রেকর্ড',clearRecords:'রেকর্ড মুছুন',localRecordsHelper:'এই রেকর্ডগুলি এই ব্রাউজারে সংরক্ষিত থাকে। এগুলি স্বয়ংক্রিয়ভাবে কোনো পৌর বিভাগে পাঠানো হয় না।',complaintsLead:'এই ডিভাইসে সংরক্ষিত রিপোর্ট দেখুন এবং তাদের স্থানীয় অবস্থা পরীক্ষা করুন.'},
    ta: {publicService:'பொது சேவை புகாரளிப்பு',language:'மொழி',reportIssue:'பிரச்சினையைப் புகாரளிக்கவும்',myComplaints:'என் புகார்கள்',citizenService:'குடிமக்கள் சேவை',reportTitle:'குடிமைப் பிரச்சினையைப் புகாரளிக்கவும்',reportLead:'பிரச்சினையைப் படம் எடுத்து, இருப்பிடத்தைச் சேர்த்து, மூன்று எளிய படிகளில் அனுப்புங்கள்.',lowConnectivity:'குறைந்த இணைப்புக்காக வடிவமைக்கப்பட்டது',snapUpload:'படம் எடுக்க / பதிவேற்ற',photoLocation:'படம் + இருப்பிடம்',categorize:'வகைப்படுத்தவும்',typeSeverityNote:'வகை + தீவிரம் + விவரம்',submit:'சமர்ப்பிக்கவும்',getTrackingId:'கண்காணிப்பு எண்ணைப் பெறவும்',location:'இருப்பிடம்',confirmLocation:'பிரச்சினையின் இருப்பிடத்தை உறுதிப்படுத்தவும்',notVerified:'சரிபார்க்கப்படவில்லை',locationHelper:'பொறுப்பான உள்ளாட்சி அமைப்பு இடத்தை அடையாளம் காண, இருப்பிடம் ஆதாரத்துடன் இணைக்கப்படுகிறது.',consentText:'இந்தப் புகாருடன் எனது தற்போதைய இருப்பிடத்தை இணைக்க ஒப்புக்கொள்கிறேன்.',verifyLocation:'என் இருப்பிடத்தைச் சரிபார்க்கவும்',photoEvidence:'புகைப்பட ஆதாரம்',showProblem:'பிரச்சினையைத் தெளிவாகக் காட்டவும்',cameraPreview:'கேமரா முன்னோட்டம்',cameraInstruction:'பிரச்சினையைப் படம் எடுக்க கேமராவைப் பயன்படுத்தவும்',openCamera:'கேமராவைத் திறக்கவும்',takePhoto:'படம் எடுக்கவும்',capturedPhoto:'எடுக்கப்பட்ட படம்',reviewBeforeSaving:'சேமிப்பதற்கு முன் சரிபார்க்கவும்',issueCategory:'பிரச்சினை வகை',selectCategory:'வகையைத் தேர்ந்தெடுக்கவும்',severity:'தீவிரம்',describeIssue:'பிரச்சினையை விவரிக்கவும்',voiceAvailable:'உங்கள் உலாவி ஆதரித்தால் குரல் உள்ளீடு கிடைக்கும்.',saveContinue:'ஆதாரத்தைச் சேமித்து தொடரவும்',reportSavedLocal:'புகார் இந்தச் சாதனத்தில் சேமிக்கப்பட்டது',trackingReference:'உங்கள் கண்காணிப்பு குறிப்பு',trackingHelper:'பின்தொடரும்போது இந்தக் குறிப்பைப் பயன்படுத்தவும். CivicTrack சேவையுடன் இணைக்கப்படும் வரை அதிகாரப்பூர்வ நிலை கிடைக்காது.',savedEvidence:'சேமிக்கப்பட்ட ஆதாரம்',localRecords:'உங்கள் உள்ளூர் பதிவுகள்',clearRecords:'பதிவுகளை அழிக்கவும்',localRecordsHelper:'இந்தப் பதிவுகள் இந்த உலாவியில் சேமிக்கப்படும். அவை தானாக எந்த நகராட்சி துறைக்கும் அனுப்பப்படாது.',complaintsLead:'இந்தச் சாதனத்தில் சேமிக்கப்பட்ட அறிக்கைகளைப் பார்த்து அவற்றின் உள்ளூர் நிலையைச் சரிபார்க்கவும்.'},
    te: {publicService:'ప్రజా సేవా నివేదికలు',language:'భాష',reportIssue:'సమస్యను నివేదించండి',myComplaints:'నా ఫిర్యాదులు',citizenService:'పౌర సేవ',reportTitle:'పౌర సమస్యను నివేదించండి',reportLead:'సమస్యను ఫోటో తీసి, స్థానాన్ని జోడించి, మూడు సులభమైన దశల్లో నివేదిక పంపండి.',lowConnectivity:'తక్కువ కనెక్టివిటీ కోసం రూపొందించబడింది',snapUpload:'ఫోటో తీయండి / అప్‌లోడ్ చేయండి',photoLocation:'ఫోటో + స్థానం',categorize:'వర్గీకరించండి',typeSeverityNote:'రకం + తీవ్రత + వివరాలు',submit:'సమర్పించండి',getTrackingId:'ట్రాకింగ్ ఐడీ పొందండి',location:'స్థానం',confirmLocation:'సమస్య స్థలాన్ని నిర్ధారించండి',notVerified:'ధృవీకరించలేదు',locationHelper:'బాధ్యత వహించే స్థానిక సంస్థ స్థలాన్ని గుర్తించడానికి స్థానం ఆధారంతో జతచేయబడుతుంది.',consentText:'ఈ నివేదికకు నా ప్రస్తుత స్థానాన్ని జోడించడానికి నేను అంగీకరిస్తున్నాను.',verifyLocation:'నా స్థానాన్ని ధృవీకరించండి',photoEvidence:'ఫోటో ఆధారం',showProblem:'సమస్యను స్పష్టంగా చూపండి',cameraPreview:'కెమెరా ప్రివ్యూ',cameraInstruction:'సమస్యను ఫోటో తీయడానికి కెమెరాను ఉపయోగించండి',openCamera:'కెమెరా తెరవండి',takePhoto:'ఫోటో తీయండి',capturedPhoto:'తీసిన ఫోటో',reviewBeforeSaving:'సేవ్ చేయడానికి ముందు పరిశీలించండి',issueCategory:'సమస్య వర్గం',selectCategory:'వర్గాన్ని ఎంచుకోండి',severity:'తీవ్రత',describeIssue:'సమస్యను వివరించండి',voiceAvailable:'బ్రౌజర్ మద్దతు ఉంటే వాయిస్ ఇన్‌పుట్ అందుబాటులో ఉంటుంది.',saveContinue:'ఆధారాన్ని సేవ్ చేసి కొనసాగండి',reportSavedLocal:'నివేదిక ఈ పరికరంలో సేవ్ చేయబడింది',trackingReference:'మీ ట్రాకింగ్ సూచన',trackingHelper:'తదుపరి అనుసరణకు ఈ సూచనను ఉపయోగించండి. CivicTrack సేవకు కనెక్ట్ అయ్యే వరకు అధికారిక విభాగ స్థితి అందుబాటులో ఉండదు.',savedEvidence:'సేవ్ చేసిన ఆధారం',localRecords:'మీ స్థానిక రికార్డులు',clearRecords:'రికార్డులను క్లియర్ చేయండి',localRecordsHelper:'ఈ రికార్డులు ఈ బ్రౌజర్‌లో నిల్వ చేయబడతాయి. అవి స్వయంచాలకంగా ఏ మునిసిపల్ విభాగానికీ పంపబడవు.',complaintsLead:'ఈ పరికరంలో సేవ్ చేసిన నివేదికలను చూడండి మరియు వాటి స్థానిక స్థితిని తనిఖీ చేయండి.'},
    mr: {publicService:'सार्वजनिक सेवा अहवाल',language:'भाषा',reportIssue:'समस्या नोंदवा',myComplaints:'माझ्या तक्रारी',citizenService:'नागरिक सेवा',reportTitle:'नागरिक समस्या नोंदवा',reportLead:'समस्येचा फोटो घ्या, स्थान जोडा आणि तीन सोप्या टप्प्यांत अहवाल पाठवा.',lowConnectivity:'कमी कनेक्टिव्हिटीसाठी तयार',snapUpload:'फोटो घ्या / अपलोड करा',photoLocation:'फोटो + स्थान',categorize:'वर्गीकरण करा',typeSeverityNote:'प्रकार + तीव्रता + तपशील',submit:'सबमिट करा',getTrackingId:'ट्रॅकिंग आयडी मिळवा',location:'स्थान',confirmLocation:'समस्येचे स्थान निश्चित करा',notVerified:'सत्यापित नाही',locationHelper:'जबाबदार स्थानिक प्राधिकरणाला ठिकाण ओळखता यावे म्हणून स्थान पुराव्यासोबत जोडले जाते.',consentText:'या अहवालासोबत माझे सध्याचे स्थान जोडण्यास मी सहमत आहे.',verifyLocation:'माझे स्थान सत्यापित करा',photoEvidence:'फोटो पुरावा',showProblem:'समस्या स्पष्टपणे दाखवा',cameraPreview:'कॅमेरा पूर्वदृश्य',cameraInstruction:'समस्येचा फोटो घेण्यासाठी कॅमेरा वापरा',openCamera:'कॅमेरा उघडा',takePhoto:'फोटो घ्या',capturedPhoto:'कॅप्चर केलेला फोटो',reviewBeforeSaving:'जतन करण्यापूर्वी तपासा',issueCategory:'समस्येचा प्रकार',selectCategory:'प्रकार निवडा',severity:'तीव्रता',describeIssue:'समस्या वर्णन करा',voiceAvailable:'ब्राउझर समर्थित असल्यास आवाजाद्वारे इनपुट उपलब्ध आहे.',saveContinue:'पुरावा जतन करा आणि पुढे जा',reportSavedLocal:'अहवाल या डिव्हाइसवर जतन झाला',trackingReference:'तुमचा ट्रॅकिंग संदर्भ',trackingHelper:'पुढील पाठपुराव्यासाठी हा संदर्भ वापरा. CivicTrack सेवेशी जोडले जाईपर्यंत अधिकृत विभागीय स्थिती उपलब्ध होणार नाही.',savedEvidence:'जतन केलेला पुरावा',localRecords:'तुमचे स्थानिक रेकॉर्ड',clearRecords:'रेकॉर्ड साफ करा',localRecordsHelper:'हे रेकॉर्ड या ब्राउझरमध्ये साठवले जातात. ते आपोआप कोणत्याही नगरपालिका विभागाकडे पाठवले जात नाहीत.',complaintsLead:'या डिव्हाइसवर जतन केलेले अहवाल पाहा आणि त्यांची स्थानिक स्थिती तपासा.'},
    gu: {publicService:'જાહેર સેવા અહેવાલ',language:'ભાષા',reportIssue:'સમસ્યા નોંધાવો',myComplaints:'મારી ફરિયાદો',citizenService:'નાગરિક સેવા',reportTitle:'નાગરિક સમસ્યા નોંધાવો',reportLead:'સમસ્યાનો ફોટો લો, સ્થાન ઉમેરો અને ત્રણ સરળ પગલાંમાં અહેવાલ મોકલો.',lowConnectivity:'ઓછી કનેક્ટિવિટી માટે બનાવેલ',snapUpload:'ફોટો લો / અપલોડ કરો',photoLocation:'ફોટો + સ્થાન',categorize:'વર્ગીકરણ કરો',typeSeverityNote:'પ્રકાર + ગંભીરતા + વિગત',submit:'સબમિટ કરો',getTrackingId:'ટ્રેકિંગ આઈડી મેળવો',location:'સ્થાન',confirmLocation:'સમસ્યાનું સ્થાન ખાતરી કરો',notVerified:'ચકાસાયેલ નથી',locationHelper:'જવાબદાર સ્થાનિક સત્તાધિકારી સ્થળ ઓળખી શકે તે માટે સ્થાન પુરાવા સાથે જોડવામાં આવે છે.',consentText:'આ અહેવાલ સાથે મારું વર્તમાન સ્થાન જોડવા માટે હું સંમત છું.',verifyLocation:'મારું સ્થાન ચકાસો',photoEvidence:'ફોટો પુરાવો',showProblem:'સમસ્યા સ્પષ્ટ રીતે બતાવો',cameraPreview:'કેમેરા પૂર્વાવલોકન',cameraInstruction:'સમસ્યાનો ફોટો લેવા કેમેરાનો ઉપયોગ કરો',openCamera:'કેમેરા ખોલો',takePhoto:'ફોટો લો',capturedPhoto:'લેવામાં આવેલ ફોટો',reviewBeforeSaving:'સાચવતા પહેલાં તપાસો',issueCategory:'સમસ્યાની શ્રેણી',selectCategory:'શ્રેણી પસંદ કરો',severity:'ગંભીરતા',describeIssue:'સમસ્યાનું વર્ણન કરો',voiceAvailable:'બ્રાઉઝર સપોર્ટ કરે ત્યારે અવાજ ઇનપુટ ઉપલબ્ધ છે.',saveContinue:'પુરાવો સાચવો અને આગળ વધો',reportSavedLocal:'અહેવાલ આ ઉપકરણ પર સાચવાયો',trackingReference:'તમારો ટ્રેકિંગ સંદર્ભ',trackingHelper:'ફોલોઅપ કરતી વખતે આ સંદર્ભનો ઉપયોગ કરો. CivicTrack સેવા સાથે જોડાણ થાય ત્યાં સુધી સત્તાવાર વિભાગીય સ્થિતિ ઉપલબ્ધ રહેશે નહીં.',savedEvidence:'સાચવેલ પુરાવો',localRecords:'તમારા સ્થાનિક રેકોર્ડ',clearRecords:'રેકોર્ડ સાફ કરો',localRecordsHelper:'આ રેકોર્ડ આ બ્રાઉઝરમાં સંગ્રહિત છે. તે આપમેળે કોઈ મ્યુનિસિપલ વિભાગને મોકલાતા નથી.',complaintsLead:'આ ઉપકરણ પર સાચવેલા અહેવાલો જુઓ અને તેમની સ્થાનિક સ્થિતિ તપાસો.'},
    kn: {publicService:'ಸಾರ್ವಜನಿಕ ಸೇವಾ ವರದಿ',language:'ಭಾಷೆ',reportIssue:'ಸಮಸ್ಯೆ ವರದಿ ಮಾಡಿ',myComplaints:'ನನ್ನ ದೂರುಗಳು',citizenService:'ನಾಗರಿಕ ಸೇವೆ',reportTitle:'ನಾಗರಿಕ ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಿ',reportLead:'ಸಮಸ್ಯೆಯ ಚಿತ್ರ ತೆಗೆದು, ಸ್ಥಳ ಸೇರಿಸಿ ಮತ್ತು ಮೂರು ಸರಳ ಹಂತಗಳಲ್ಲಿ ವರದಿ ಕಳುಹಿಸಿ.',lowConnectivity:'ಕಡಿಮೆ ಸಂಪರ್ಕಕ್ಕಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಲಾಗಿದೆ',snapUpload:'ಚಿತ್ರ ತೆಗೆ / ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',photoLocation:'ಚಿತ್ರ + ಸ್ಥಳ',categorize:'ವರ್ಗೀಕರಿಸಿ',typeSeverityNote:'ಪ್ರಕಾರ + ತೀವ್ರತೆ + ವಿವರ',submit:'ಸಲ್ಲಿಸಿ',getTrackingId:'ಟ್ರ್ಯಾಕಿಂಗ್ ಐಡಿ ಪಡೆಯಿರಿ',location:'ಸ್ಥಳ',confirmLocation:'ಸಮಸ್ಯೆಯ ಸ್ಥಳವನ್ನು ದೃಢೀಕರಿಸಿ',notVerified:'ಪರಿಶೀಲಿಸಲಾಗಿಲ್ಲ',locationHelper:'ಜವಾಬ್ದಾರಿಯುತ ಸ್ಥಳೀಯ ಸಂಸ್ಥೆ ಸ್ಥಳವನ್ನು ಗುರುತಿಸಲು ಸ್ಥಳವನ್ನು ಸಾಕ್ಷ್ಯಕ್ಕೆ ಜೋಡಿಸಲಾಗುತ್ತದೆ.',consentText:'ಈ ವರದಿಗೆ ನನ್ನ ಪ್ರಸ್ತುತ ಸ್ಥಳವನ್ನು ಜೋಡಿಸಲು ನಾನು ಒಪ್ಪುತ್ತೇನೆ.',verifyLocation:'ನನ್ನ ಸ್ಥಳ ಪರಿಶೀಲಿಸಿ',photoEvidence:'ಚಿತ್ರ ಸಾಕ್ಷ್ಯ',showProblem:'ಸಮಸ್ಯೆಯನ್ನು ಸ್ಪಷ್ಟವಾಗಿ ತೋರಿಸಿ',cameraPreview:'ಕ್ಯಾಮೆರಾ ಪೂರ್ವವೀಕ್ಷಣೆ',cameraInstruction:'ಸಮಸ್ಯೆಯ ಚಿತ್ರ ತೆಗೆಯಲು ಕ್ಯಾಮೆರಾ ಬಳಸಿ',openCamera:'ಕ್ಯಾಮೆರಾ ತೆರೆಯಿರಿ',takePhoto:'ಚಿತ್ರ ತೆಗೆಯಿರಿ',capturedPhoto:'ತೆಗೆದ ಚಿತ್ರ',reviewBeforeSaving:'ಉಳಿಸುವ ಮೊದಲು ಪರಿಶೀಲಿಸಿ',issueCategory:'ಸಮಸ್ಯೆಯ ವರ್ಗ',selectCategory:'ವರ್ಗ ಆಯ್ಕೆಮಾಡಿ',severity:'ತೀವ್ರತೆ',describeIssue:'ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಿ',voiceAvailable:'ಬ್ರೌಸರ್ ಬೆಂಬಲಿಸಿದರೆ ಧ್ವನಿ ಇನ್‌ಪುಟ್ ಲಭ್ಯವಿದೆ.',saveContinue:'ಸಾಕ್ಷ್ಯ ಉಳಿಸಿ ಮತ್ತು ಮುಂದುವರಿಯಿರಿ',reportSavedLocal:'ವರದಿ ಈ ಸಾಧನದಲ್ಲಿ ಉಳಿಸಲಾಗಿದೆ',trackingReference:'ನಿಮ್ಮ ಟ್ರ್ಯಾಕಿಂಗ್ ಉಲ್ಲೇಖ',trackingHelper:'ಮುಂದಿನ ವಿಚಾರಣೆಗೆ ಈ ಉಲ್ಲೇಖ ಬಳಸಿ. CivicTrack ಸೇವೆಗೆ ಸಂಪರ್ಕಿಸುವವರೆಗೆ ಅಧಿಕೃತ ಇಲಾಖಾ ಸ್ಥಿತಿ ಲಭ್ಯವಿರುವುದಿಲ್ಲ.',savedEvidence:'ಉಳಿಸಿದ ಸಾಕ್ಷ್ಯ',localRecords:'ನಿಮ್ಮ ಸ್ಥಳೀಯ ದಾಖಲೆಗಳು',clearRecords:'ದಾಖಲೆಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ',localRecordsHelper:'ಈ ದಾಖಲೆಗಳು ಈ ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಉಳಿಯುತ್ತವೆ. ಅವು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಯಾವುದೇ ಪುರಸಭಾ ಇಲಾಖೆಗೆ ಕಳುಹಿಸಲಾಗುವುದಿಲ್ಲ.',complaintsLead:'ಈ ಸಾಧನದಲ್ಲಿ ಉಳಿಸಿದ ವರದಿಗಳನ್ನು ನೋಡಿ ಮತ್ತು ಅವುಗಳ ಸ್ಥಳೀಯ ಸ್ಥಿತಿಯನ್ನು ಪರಿಶೀಲಿಸಿ.'},
    ml: {publicService:'പൊതു സേവന റിപ്പോർട്ടിംഗ്',language:'ഭാഷ',reportIssue:'പ്രശ്നം റിപ്പോർട്ട് ചെയ്യുക',myComplaints:'എന്റെ പരാതികൾ',citizenService:'പൗര സേവനം',reportTitle:'പൗര പ്രശ്നം റിപ്പോർട്ട് ചെയ്യുക',reportLead:'പ്രശ്നത്തിന്റെ ചിത്രം എടുക്കുക, സ്ഥലം ചേർക്കുക, മൂന്ന് ലളിത ഘട്ടങ്ങളിൽ റിപ്പോർട്ട് അയയ്ക്കുക.',lowConnectivity:'കുറഞ്ഞ കണക്റ്റിവിറ്റിക്കായി രൂപകൽപ്പന ചെയ്തത്',snapUpload:'ചിത്രം എടുക്കുക / അപ്‌ലോഡ് ചെയ്യുക',photoLocation:'ചിത്രം + സ്ഥലം',categorize:'വർഗ്ഗീകരിക്കുക',typeSeverityNote:'തരം + ഗൗരവം + വിശദാംശങ്ങൾ',submit:'സമർപ്പിക്കുക',getTrackingId:'ട്രാക്കിംഗ് ഐഡി നേടുക',location:'സ്ഥലം',confirmLocation:'പ്രശ്നത്തിന്റെ സ്ഥലം സ്ഥിരീകരിക്കുക',notVerified:'സ്ഥിരീകരിച്ചിട്ടില്ല',locationHelper:'ഉത്തരവാദപ്പെട്ട പ്രാദേശിക അധികാരികൾക്ക് സ്ഥലം തിരിച്ചറിയാൻ കഴിയുന്നതിനായി സ്ഥലം തെളിവിനൊപ്പം ചേർക്കുന്നു.',consentText:'ഈ റിപ്പോർട്ടിനൊപ്പം എന്റെ നിലവിലെ സ്ഥലം ചേർക്കാൻ ഞാൻ സമ്മതിക്കുന്നു.',verifyLocation:'എന്റെ സ്ഥലം സ്ഥിരീകരിക്കുക',photoEvidence:'ഫോട്ടോ തെളിവ്',showProblem:'പ്രശ്നം വ്യക്തമായി കാണിക്കുക',cameraPreview:'ക്യാമറ പ്രിവ്യൂ',cameraInstruction:'പ്രശ്നത്തിന്റെ ചിത്രം എടുക്കാൻ ക്യാമറ ഉപയോഗിക്കുക',openCamera:'ക്യാമറ തുറക്കുക',takePhoto:'ചിത്രം എടുക്കുക',capturedPhoto:'പകർത്തിയ ചിത്രം',reviewBeforeSaving:'സംരക്ഷിക്കുന്നതിന് മുമ്പ് പരിശോധിക്കുക',issueCategory:'പ്രശ്നത്തിന്റെ വിഭാഗം',selectCategory:'വിഭാഗം തിരഞ്ഞെടുക്കുക',severity:'ഗൗരവം',describeIssue:'പ്രശ്നം വിവരിക്കുക',voiceAvailable:'ബ്രൗസർ പിന്തുണയ്ക്കുന്നുവെങ്കിൽ വോയ്സ് ഇൻപുട്ട് ലഭ്യമാണ്.',saveContinue:'തെളിവ് സംരക്ഷിച്ച് തുടരുക',reportSavedLocal:'റിപ്പോർട്ട് ഈ ഉപകരണത്തിൽ സംരക്ഷിച്ചു',trackingReference:'നിങ്ങളുടെ ട്രാക്കിംഗ് റഫറൻസ്',trackingHelper:'തുടർനടപടികൾക്കായി ഈ റഫറൻസ് ഉപയോഗിക്കുക. CivicTrack സേവനവുമായി ബന്ധിപ്പിക്കുന്നതുവരെ ഔദ്യോഗിക വകുപ്പുതല സ്ഥിതി ലഭ്യമാകില്ല.',savedEvidence:'സംരക്ഷിച്ച തെളിവ്',localRecords:'നിങ്ങളുടെ പ്രാദേശിക രേഖകൾ',clearRecords:'രേഖകൾ മായ്ക്കുക',localRecordsHelper:'ഈ രേഖകൾ ഈ ബ്രൗസറിൽ സൂക്ഷിക്കുന്നു. അവ സ്വയമേവ ഏതെങ്കിലും മുനിസിപ്പൽ വകുപ്പിലേക്ക് അയയ്ക്കില്ല.',complaintsLead:'ഈ ഉപകരണത്തിൽ സംരക്ഷിച്ച റിപ്പോർട്ടുകൾ കാണുകയും അവയുടെ പ്രാദേശിക സ്ഥിതി പരിശോധിക്കുകയും ചെയ്യുക.'},
    or: {publicService:'ସାର୍ବଜନୀନ ସେବା ରିପୋର୍ଟିଂ',language:'ଭାଷା',reportIssue:'ସମସ୍ୟା ରିପୋର୍ଟ କରନ୍ତୁ',myComplaints:'ମୋ ଅଭିଯୋଗ',citizenService:'ନାଗରିକ ସେବା',reportTitle:'ନାଗରିକ ସମସ୍ୟା ରିପୋର୍ଟ କରନ୍ତୁ',reportLead:'ସମସ୍ୟାର ଫଟୋ ନିଅନ୍ତୁ, ସ୍ଥାନ ଯୋଡନ୍ତୁ ଏବଂ ତିନୋଟି ସହଜ ପଦକ୍ଷେପରେ ରିପୋର୍ଟ ପଠାନ୍ତୁ।',lowConnectivity:'କମ୍ ସଂଯୋଗ ପାଇଁ ତିଆରି',snapUpload:'ଫଟୋ ନିଅନ୍ତୁ / ଅପଲୋଡ୍ କରନ୍ତୁ',photoLocation:'ଫଟୋ + ସ୍ଥାନ',categorize:'ଶ୍ରେଣୀବଦ୍ଧ କରନ୍ତୁ',typeSeverityNote:'ପ୍ରକାର + ଗୁରୁତ୍ୱ + ବିବରଣୀ',submit:'ଦାଖଲ କରନ୍ତୁ',getTrackingId:'ଟ୍ରାକିଂ ଆଇଡି ପାଆନ୍ତୁ',location:'ସ୍ଥାନ',confirmLocation:'ସମସ୍ୟାର ସ୍ଥାନ ନିଶ୍ଚିତ କରନ୍ତୁ',notVerified:'ଯାଞ୍ଚ ହୋଇନାହିଁ',locationHelper:'ଦାୟିତ୍ୱଶୀଳ ସ୍ଥାନୀୟ କର୍ତ୍ତୃପକ୍ଷ ସ୍ଥାନ ଚିହ୍ନଟ କରିପାରିବା ପାଇଁ ସ୍ଥାନଟି ପ୍ରମାଣ ସହିତ ଯୋଡାଯାଏ।',consentText:'ଏହି ରିପୋର୍ଟ ସହିତ ମୋର ବର୍ତ୍ତମାନର ସ୍ଥାନ ଯୋଡିବାକୁ ମୁଁ ସମ୍ମତ।',verifyLocation:'ମୋ ସ୍ଥାନ ଯାଞ୍ଚ କରନ୍ତୁ',photoEvidence:'ଫଟୋ ପ୍ରମାଣ',showProblem:'ସମସ୍ୟାକୁ ସ୍ପଷ୍ଟ ଭାବେ ଦେଖାନ୍ତୁ',cameraPreview:'କ୍ୟାମେରା ପୂର୍ବଦୃଶ୍ୟ',cameraInstruction:'ସମସ୍ୟାର ଫଟୋ ନେବା ପାଇଁ କ୍ୟାମେରା ବ୍ୟବହାର କରନ୍ତୁ',openCamera:'କ୍ୟାମେରା ଖୋଲନ୍ତୁ',takePhoto:'ଫଟୋ ନିଅନ୍ତୁ',capturedPhoto:'ତୋଳା ଫଟୋ',reviewBeforeSaving:'ସଞ୍ଚୟ ପୂର୍ବରୁ ଯାଞ୍ଚ କରନ୍ତୁ',issueCategory:'ସମସ୍ୟା ଶ୍ରେଣୀ',selectCategory:'ଶ୍ରେଣୀ ବାଛନ୍ତୁ',severity:'ଗୁରୁତ୍ୱ',describeIssue:'ସମସ୍ୟା ବର୍ଣ୍ଣନା କରନ୍ତୁ',voiceAvailable:'ବ୍ରାଉଜର ସମର୍ଥନ କଲେ ଭଏସ୍ ଇନପୁଟ୍ ଉପଲବ୍ଧ।',saveContinue:'ପ୍ରମାଣ ସଞ୍ଚୟ କରି ଜାରି ରଖନ୍ତୁ',reportSavedLocal:'ରିପୋର୍ଟ ଏହି ଡିଭାଇସରେ ସଞ୍ଚୟ ହୋଇଛି',trackingReference:'ଆପଣଙ୍କ ଟ୍ରାକିଂ ରେଫରେନ୍ସ',trackingHelper:'ପରବର୍ତ୍ତୀ ଅନୁସରଣ ପାଇଁ ଏହି ରେଫରେନ୍ସ ବ୍ୟବହାର କରନ୍ତୁ। CivicTrack ସେବା ସହିତ ସଂଯୋଗ ହେବା ପର୍ଯ୍ୟନ୍ତ ସରକାରୀ ବିଭାଗୀୟ ସ୍ଥିତି ଉପଲବ୍ଧ ହେବ ନାହିଁ।',savedEvidence:'ସଞ୍ଚୟ ହୋଇଥିବା ପ୍ରମାଣ',localRecords:'ଆପଣଙ୍କ ସ୍ଥାନୀୟ ରେକର୍ଡ',clearRecords:'ରେକର୍ଡ ସଫା କରନ୍ତୁ',localRecordsHelper:'ଏହି ରେକର୍ଡଗୁଡିକ ଏହି ବ୍ରାଉଜରରେ ସଞ୍ଚୟ ହୁଏ। ସେଗୁଡିକ ସ୍ୱୟଂଚାଳିତ ଭାବରେ କୌଣସି ପୌର ବିଭାଗକୁ ପଠାଯାଏ ନାହିଁ।',complaintsLead:'ଏହି ଡିଭାଇସରେ ସଞ୍ଚୟ ହୋଇଥିବା ରିପୋର୍ଟଗୁଡିକ ଦେଖନ୍ତୁ ଏବଂ ସେମାନଙ୍କର ସ୍ଥାନୀୟ ସ୍ଥିତି ଯାଞ୍ଚ କରନ୍ତୁ।'},
    pa: {publicService:'ਜਨਤਕ ਸੇਵਾ ਰਿਪੋਰਟਿੰਗ',language:'ਭਾਸ਼ਾ',reportIssue:'ਸਮੱਸਿਆ ਦੀ ਰਿਪੋਰਟ ਕਰੋ',myComplaints:'ਮੇਰੀਆਂ ਸ਼ਿਕਾਇਤਾਂ',citizenService:'ਨਾਗਰਿਕ ਸੇਵਾ',reportTitle:'ਨਾਗਰਿਕ ਸਮੱਸਿਆ ਦੀ ਰਿਪੋਰਟ ਕਰੋ',reportLead:'ਸਮੱਸਿਆ ਦੀ ਤਸਵੀਰ ਲਓ, ਸਥਾਨ ਸ਼ਾਮਲ ਕਰੋ ਅਤੇ ਤਿੰਨ ਸੌਖੇ ਕਦਮਾਂ ਵਿੱਚ ਰਿਪੋਰਟ ਭੇਜੋ।',lowConnectivity:'ਘੱਟ ਕਨੈਕਟੀਵਿਟੀ ਲਈ ਬਣਾਇਆ ਗਿਆ',snapUpload:'ਫੋਟੋ ਲਓ / ਅਪਲੋਡ ਕਰੋ',photoLocation:'ਫੋਟੋ + ਸਥਾਨ',categorize:'ਸ਼੍ਰੇਣੀਬੱਧ ਕਰੋ',typeSeverityNote:'ਕਿਸਮ + ਗੰਭੀਰਤਾ + ਵੇਰਵਾ',submit:'ਜਮ੍ਹਾਂ ਕਰੋ',getTrackingId:'ਟ੍ਰੈਕਿੰਗ ਆਈਡੀ ਪ੍ਰਾਪਤ ਕਰੋ',location:'ਸਥਾਨ',confirmLocation:'ਸਮੱਸਿਆ ਦਾ ਸਥਾਨ ਪੱਕਾ ਕਰੋ',notVerified:'ਤਸਦੀਕ ਨਹੀਂ ਹੋਈ',locationHelper:'ਜ਼ਿੰਮੇਵਾਰ ਸਥਾਨਕ ਅਥਾਰਟੀ ਸਥਾਨ ਦੀ ਪਛਾਣ ਕਰ ਸਕੇ, ਇਸ ਲਈ ਸਥਾਨ ਨੂੰ ਸਬੂਤ ਨਾਲ ਜੋੜਿਆ ਜਾਂਦਾ ਹੈ।',consentText:'ਮੈਂ ਇਸ ਰਿਪੋਰਟ ਨਾਲ ਆਪਣਾ ਮੌਜੂਦਾ ਸਥਾਨ ਜੋੜਨ ਲਈ ਸਹਿਮਤ ਹਾਂ।',verifyLocation:'ਮੇਰਾ ਸਥਾਨ ਤਸਦੀਕ ਕਰੋ',photoEvidence:'ਫੋਟੋ ਸਬੂਤ',showProblem:'ਸਮੱਸਿਆ ਨੂੰ ਸਪਸ਼ਟ ਦਿਖਾਓ',cameraPreview:'ਕੈਮਰਾ ਝਲਕ',cameraInstruction:'ਸਮੱਸਿਆ ਦੀ ਤਸਵੀਰ ਲੈਣ ਲਈ ਕੈਮਰਾ ਵਰਤੋ',openCamera:'ਕੈਮਰਾ ਖੋਲ੍ਹੋ',takePhoto:'ਫੋਟੋ ਲਓ',capturedPhoto:'ਖਿੱਚੀ ਫੋਟੋ',reviewBeforeSaving:'ਸੰਭਾਲਣ ਤੋਂ ਪਹਿਲਾਂ ਜਾਂਚੋ',issueCategory:'ਸਮੱਸਿਆ ਦੀ ਸ਼੍ਰੇਣੀ',selectCategory:'ਸ਼੍ਰੇਣੀ ਚੁਣੋ',severity:'ਗੰਭੀਰਤਾ',describeIssue:'ਸਮੱਸਿਆ ਦਾ ਵੇਰਵਾ ਦਿਓ',voiceAvailable:'ਬ੍ਰਾਊਜ਼ਰ ਸਹਾਇਤਾ ਕਰੇ ਤਾਂ ਆਵਾਜ਼ ਇਨਪੁਟ ਉਪਲਬਧ ਹੈ।',saveContinue:'ਸਬੂਤ ਸੰਭਾਲੋ ਅਤੇ ਜਾਰੀ ਰੱਖੋ',reportSavedLocal:'ਰਿਪੋਰਟ ਇਸ ਡਿਵਾਈਸ ਉੱਤੇ ਸੰਭਾਲੀ ਗਈ',trackingReference:'ਤੁਹਾਡਾ ਟ੍ਰੈਕਿੰਗ ਹਵਾਲਾ',trackingHelper:'ਫਾਲੋ-ਅੱਪ ਲਈ ਇਹ ਹਵਾਲਾ ਵਰਤੋ। CivicTrack ਸੇਵਾ ਨਾਲ ਕਨੈਕਸ਼ਨ ਹੋਣ ਤੱਕ ਅਧਿਕਾਰਤ ਵਿਭਾਗੀ ਸਥਿਤੀ ਉਪਲਬਧ ਨਹੀਂ ਹੋਵੇਗੀ।',savedEvidence:'ਸੰਭਾਲਿਆ ਸਬੂਤ',localRecords:'ਤੁਹਾਡੇ ਸਥਾਨਕ ਰਿਕਾਰਡ',clearRecords:'ਰਿਕਾਰਡ ਸਾਫ਼ ਕਰੋ',localRecordsHelper:'ਇਹ ਰਿਕਾਰਡ ਇਸ ਬ੍ਰਾਊਜ਼ਰ ਵਿੱਚ ਸਟੋਰ ਹੁੰਦੇ ਹਨ। ਇਹ ਆਪਣੇ ਆਪ ਕਿਸੇ ਨਗਰ ਨਿਗਮ ਵਿਭਾਗ ਨੂੰ ਨਹੀਂ ਭੇਜੇ ਜਾਂਦੇ।',complaintsLead:'ਇਸ ਡਿਵਾਈਸ ਉੱਤੇ ਸੰਭਾਲੀਆਂ ਰਿਪੋਰਟਾਂ ਵੇਖੋ ਅਤੇ ਉਨ੍ਹਾਂ ਦੀ ਸਥਾਨਕ ਸਥਿਤੀ ਜਾਂਚੋ.'},
    ur: {publicService:'عوامی خدمت رپورٹنگ',language:'زبان',reportIssue:'مسئلے کی اطلاع دیں',myComplaints:'میری شکایات',citizenService:'شہری خدمت',reportTitle:'شہری مسئلے کی اطلاع دیں',reportLead:'مسئلے کی تصویر لیں، مقام شامل کریں اور تین آسان مراحل میں رپورٹ بھیجیں۔',lowConnectivity:'کم کنیکٹیویٹی کے لیے بنایا گیا',snapUpload:'تصویر لیں / اپ لوڈ کریں',photoLocation:'تصویر + مقام',categorize:'درجہ بندی کریں',typeSeverityNote:'قسم + شدت + تفصیل',submit:'جمع کریں',getTrackingId:'ٹریکنگ آئی ڈی حاصل کریں',location:'مقام',confirmLocation:'مسئلے کے مقام کی تصدیق کریں',notVerified:'تصدیق نہیں ہوئی',locationHelper:'مقام کو ثبوت کے ساتھ منسلک کیا جاتا ہے تاکہ متعلقہ مقامی ادارہ جگہ کی شناخت کر سکے۔',consentText:'میں اس رپورٹ کے ساتھ اپنا موجودہ مقام منسلک کرنے پر رضامند ہوں۔',verifyLocation:'میرا مقام تصدیق کریں',photoEvidence:'تصویری ثبوت',showProblem:'مسئلہ واضح طور پر دکھائیں',cameraPreview:'کیمرہ پیش نظارہ',cameraInstruction:'مسئلے کی تصویر لینے کے لیے کیمرہ استعمال کریں',openCamera:'کیمرہ کھولیں',takePhoto:'تصویر لیں',capturedPhoto:'لی گئی تصویر',reviewBeforeSaving:'محفوظ کرنے سے پہلے جائزہ لیں',issueCategory:'مسئلے کی قسم',selectCategory:'قسم منتخب کریں',severity:'شدت',describeIssue:'مسئلہ بیان کریں',voiceAvailable:'اگر براؤزر معاونت کرتا ہو تو صوتی ان پٹ دستیاب ہے۔',saveContinue:'ثبوت محفوظ کریں اور جاری رکھیں',reportSavedLocal:'رپورٹ اس ڈیوائس پر محفوظ ہے',trackingReference:'آپ کا ٹریکنگ حوالہ',trackingHelper:'فالو اپ کے لیے یہ حوالہ استعمال کریں۔ CivicTrack سروس سے رابطہ ہونے تک سرکاری محکمانہ حیثیت دستیاب نہیں ہوگی۔',savedEvidence:'محفوظ شدہ ثبوت',localRecords:'آپ کے مقامی ریکارڈ',clearRecords:'ریکارڈ صاف کریں',localRecordsHelper:'یہ ریکارڈ اسی براؤزر میں محفوظ ہیں۔ انہیں خودکار طور پر کسی بلدیاتی محکمے کو نہیں بھیجا جاتا۔',complaintsLead:'اس ڈیوائس پر محفوظ رپورٹس دیکھیں اور ان کی مقامی حیثیت چیک کریں۔'}
  };

  const categoryTranslations = {
    hi:['पॉथोल / क्षतिग्रस्त सड़क','कचरा / स्वच्छता','स्ट्रीट लाइट','पानी का रिसाव','जल निकासी / बाढ़','बिजली','सार्वजनिक संपत्ति को नुकसान','अन्य'],
    as:['গাঁত / ক্ষতিগ্ৰস্ত পথ','আৱৰ্জনা / পৰিষ্কাৰ-পৰিচ্ছন্নতা','পথবাতি','পানীৰ লিকেজ','নলা / বানপানী','বিদ্যুৎ','ৰাজহুৱা সম্পত্তিৰ ক্ষতি','অন্যান্য'],
    bn:['গর্ত / ক্ষতিগ্রস্ত রাস্তা','আবর্জনা / স্যানিটেশন','স্ট্রিটলাইট','জল লিকেজ','নর্দমা / জলাবদ্ধতা','বিদ্যুৎ','সরকারি সম্পত্তির ক্ষতি','অন্যান্য'],
    ta:['சாலையில் பள்ளம் / சேதமான சாலை','குப்பை / சுகாதாரம்','தெருவிளக்கு','நீர் கசிவு','வடிகால் / வெள்ளம்','மின்சாரம்','பொது சொத்து சேதம்','மற்றவை'],
    te:['గుంత / దెబ్బతిన్న రహదారి','చెత్త / పారిశుధ్యం','వీధి దీపం','నీటి లీకేజీ','డ్రైనేజీ / వరద','విద్యుత్','ప్రజా ఆస్తి నష్టం','ఇతర'],
    mr:['खड्डा / खराब रस्ता','कचरा / स्वच्छता','पथदिवा','पाणी गळती','निचरा / पूर','वीज','सार्वजनिक मालमत्तेचे नुकसान','इतर'],
    gu:['ખાડો / ખરાબ રસ્તો','કચરો / સ્વચ્છતા','સ્ટ્રીટલાઇટ','પાણીનું લીકેજ','ડ્રેનેજ / પૂર','વીજળી','જાહેર મિલકતનું નુકસાન','અન્ય'],
    kn:['ಗುಂಡಿ / ಹಾನಿಗೊಳಗಾದ ರಸ್ತೆ','ಕಸ / ಸ್ವಚ್ಛತೆ','ಬೀದಿ ದೀಪ','ನೀರಿನ ಸೋರಿಕೆ','ಚರಂಡಿ / ನೆರೆ','ವಿದ್ಯುತ್','ಸಾರ್ವಜನಿಕ ಆಸ್ತಿ ಹಾನಿ','ಇತರೆ'],
    ml:['കുഴി / തകർന്ന റോഡ്','മാലിന്യം / ശുചിത്വം','തെരുവ് വിളക്ക്','വെള്ളം ചോർച്ച','ഡ്രെയിനേജ് / വെള്ളപ്പൊക്കം','വൈദ്യുതി','പൊതു സ്വത്ത് നാശം','മറ്റുള്ളവ'],
    or:['ଗାତ / କ୍ଷତିଗ୍ରସ୍ତ ରାସ୍ତା','ଆବର୍ଜନା / ପରିମଳ','ଷ୍ଟ୍ରିଟ୍ ଲାଇଟ୍','ପାଣି ଲିକେଜ୍','ଡ୍ରେନେଜ୍ / ବନ୍ୟା','ବିଦ୍ୟୁତ୍','ସାର୍ବଜନୀନ ସମ୍ପତ୍ତି କ୍ଷତି','ଅନ୍ୟାନ୍ୟ'],
    pa:['ਟੋਆ / ਖਰਾਬ ਸੜਕ','ਕੂੜਾ / ਸਫਾਈ','ਸਟ੍ਰੀਟ ਲਾਈਟ','ਪਾਣੀ ਦੀ ਲੀਕੇਜ','ਨਿਕਾਸੀ / ਹੜ੍ਹ','ਬਿਜਲੀ','ਜਨਤਕ ਸੰਪਤੀ ਦਾ ਨੁਕਸਾਨ','ਹੋਰ'],
    ur:['گڑھا / خراب سڑک','کچرا / صفائی','اسٹریٹ لائٹ','پانی کا رساؤ','نکاسی آب / سیلاب','بجلی','سرکاری املاک کو نقصان','دیگر']
  };

  function translatePage(lang){
    const dict = translations[lang] || translations.en;
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ur' ? 'rtl' : 'ltr';
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.dataset.i18n;
      if(!el.dataset.en) el.dataset.en = el.textContent;
      el.textContent = dict[key] || el.dataset.en;
    });
    // Translate select options without touching values used by the existing logic.
    const cat = $('issueCategory');
    if(cat && lang !== 'en' && categoryTranslations[lang]) {
      [...cat.options].slice(1).forEach((o,i)=>o.textContent=categoryTranslations[lang][i] || o.textContent);
      cat.options[0].textContent = dict.selectCategory || cat.options[0].textContent;
    } else if(cat && lang === 'en') {
      ['Select a category','Pothole / damaged road','Garbage / sanitation','Streetlight','Water leakage','Drainage / flooding','Electricity','Public property damage','Other'].forEach((x,i)=>{ if(cat.options[i]) cat.options[i].textContent=x; });
    }
    localStorage.setItem('civictrack:language', lang);
  }
  const languageSelect = $('languageSelect');
  const storedLang = localStorage.getItem('civictrack:language') || 'en';
  languageSelect.value = storedLang;
  translatePage(storedLang);
  languageSelect.addEventListener('change', e => translatePage(e.target.value));

  // Browser-native speech input; language follows the selected UI language where supported.
  const voiceBtn = $('voiceBtn');
  const voiceStatus = $('voiceStatus');
  const details = $('issueDetails');
  let recognition = null;
  const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
  const speechLocales = {en:'en-IN',hi:'hi-IN',as:'as-IN',bn:'bn-IN',gu:'gu-IN',kn:'kn-IN',ml:'ml-IN',mr:'mr-IN',or:'or-IN',pa:'pa-IN',ta:'ta-IN',te:'te-IN',ur:'ur-IN'};
  if(SpeechRecognition){
    recognition = new SpeechRecognition();
    recognition.continuous = false;
    recognition.interimResults = false;
    recognition.onstart = () => { voiceBtn.textContent = 'Listening…'; };
    recognition.onresult = (e) => { const text = e.results[0][0].transcript; details.value = details.value ? details.value.trim() + ' ' + text : text; };
    recognition.onerror = () => { voiceStatus.textContent = 'Voice input could not be used. You can type the description instead.'; };
    recognition.onend = () => { voiceBtn.textContent = 'Speak'; };
    voiceBtn.addEventListener('click', () => { recognition.lang = speechLocales[languageSelect.value] || 'en-IN'; recognition.start(); });
  } else { voiceBtn.disabled = true; }

  // Local tracking reference: deliberately remains a local reference, not a fake government ticket.
  const saveBtn = $('saveBtn');
  const ticketPanel = $('ticketPanel');
  const ticketId = $('ticketId');
  window.onReportSaved = function(record){
    ticketId.textContent = record.ticket;
    ticketPanel.hidden = false;
    localStorage.setItem('civictrack:lastTicket', record.ticket);
  };

  function refreshComplaintView(){
    const list = $('complaintList'); if(!list) return;
    const last = localStorage.getItem('civictrack:lastTicket');
    if(!last){ list.innerHTML = '<div class="complaint-card"><strong>No saved complaint on this device.</strong><p class="helper">Save an evidence record from the reporting page and its local reference will appear here.</p></div>'; return; }
    list.innerHTML = '<article class="complaint-card"><div class="complaint-top"><div><div class="eyebrow">TRACKING REFERENCE</div><div class="complaint-id">'+last+'</div><h2>Evidence report</h2></div><span class="state-badge">Saved locally</span></div><p class="helper">This is a local reference generated by the interface. Official departmental status becomes available only when the existing service backend is connected.</p><div class="status-pipeline"><span class="status-step current">Received</span><span class="status-step">Inspection scheduled</span><span class="status-step">Work in progress</span><span class="status-step">Resolved</span></div></article>';
  }
  const complaintsTab = document.querySelector('[data-view="complaintsView"]');
  if(complaintsTab) complaintsTab.addEventListener('click', refreshComplaintView);

  // Community reports: photos shared by other citizens (served by server.js)
  const API = (window.CIVICTRACK_API || '').replace(/\/$/, '');
  const escHtml = v => String(v == null ? '' : v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function loadCommunity(){
    const list = $('communityList'), st = $('communityStatus');
    st.textContent = 'Loading shared reports…';
    try{
      const items = await fetchSharedReports();
      st.textContent = items.length ? items.length + ' shared report(s)' : 'No shared reports yet. Be the first to report an issue.';
      list.innerHTML = items.map(r => '<article class="community-card">' +
        '<img src="' + escHtml(r.photoUrl) + '" alt="Photo of reported issue" loading="lazy">' +
        '<div class="community-body"><span class="state-badge">' + escHtml(r.severity) + '</span>' +
        '<h2>' + escHtml(r.category) + '</h2>' +
        (r.placeName ? '<p class="record-meta">📍 ' + escHtml(r.placeName) + '</p>' : '') +
        (r.details ? '<p>' + escHtml(r.details) + '</p>' : '') +
        '<p class="record-meta">' + new Date(r.capturedAt).toLocaleString() + ' · ' + escHtml(r.ticket) + '</p>' +
        '<a class="record-meta" target="_blank" rel="noopener" href="https://www.openstreetmap.org/?mlat=' + Number(r.latitude) + '&mlon=' + Number(r.longitude) + '#map=18/' + Number(r.latitude) + '/' + Number(r.longitude) + '">View on map</a>' +
        '</div></article>').join('');
    }catch(e){
      list.innerHTML = '';
      st.textContent = 'Could not load shared reports. Check your internet and the storage setup in config.js.';
    }
  }
  const communityTab = document.querySelector('[data-view="communityView"]');
  if(communityTab) communityTab.addEventListener('click', loadCommunity);
  $('refreshCommunity').addEventListener('click', loadCommunity);
})();
